import { useEffect, useState } from 'react';
type DocumentItem={id:string;filename:string;chunk_count:number}; type Chunk={index:number;content:string;embedding_model:string;embedding_dimensions:number};
export function KnowledgePanel({onClose}:{onClose:()=>void}){
 const [documents,setDocuments]=useState<DocumentItem[]>([]),[filename,setFilename]=useState(''),[content,setContent]=useState(''),[error,setError]=useState(''),[expanded,setExpanded]=useState<Record<string,Chunk[]>>({}),[query,setQuery]=useState(''),[results,setResults]=useState<any[]>([]);
 const load=()=>fetch('/api/v1/documents').then(r=>r.json()).then(b=>setDocuments(b.data||[])); useEffect(()=>{load().catch(()=>setError('无法加载文档'))},[]);
 const upload=async()=>{setError('');if(!filename.trim()||!content.trim())return;const b=await fetch('/api/v1/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename,content})}).then(r=>r.json());if(!b.success){setError(b.error?.message||'上传失败');return}setFilename('');setContent('');load()};
 const remove=async(id:string)=>{await fetch(`/api/v1/documents/${id}`,{method:'DELETE'});load()}; const preview=async(id:string)=>{const b=await fetch(`/api/v1/documents/${id}`).then(r=>r.json());setExpanded(e=>({...e,[id]:b.data?.chunks||[]}))}; const search=async()=>{const b=await fetch(`/api/v1/documents/search?q=${encodeURIComponent(query)}&mode=keyword`).then(r=>r.json());setResults(b.data||[])};
 return <div className="modal-backdrop"><section className="settings-panel knowledge-panel"><div className="settings-header"><h2>知识库</h2><button onClick={onClose}>关闭</button></div><input value={filename} onChange={e=>setFilename(e.target.value)} placeholder="文件名"/><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="粘贴文档内容"/><button className="save-button" onClick={upload}>上传文档</button><div className="knowledge-search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="检索知识库"/><button onClick={search}>检索</button></div>{error&&<small className="knowledge-error">{error}</small>}{documents.map(d=><div className="document-item" key={d.id}><span onClick={()=>preview(d.id)}>{d.filename}<small>{d.chunk_count} 个分块</small></span><button onClick={()=>remove(d.id)}>删除</button>{expanded[d.id]?.map(c=><pre key={c.index}>{c.content}</pre>)}</div>)}{results.map((r,i)=><div className="search-result" key={i}>{r.filename} · {r.score}<div>{r.content}</div></div>)}</section></div>;
}
